### ISSUE TITLE
Artists Profile is messed up showing black bg in half screen! plz do sumthin i really fkin luv this theme. what's the solution?

### ISSUE THREAD

**Issue by Shybunbro** [harbassan/spicetify-galaxy#73]
![Screenshot 2024-05-05 114014](https://github.com/harbassan/spicetify-galaxy/assets/168953708/232d3c45-629e-4735-8f79-96c525576905)

**Comment by Hrushal-Nikhare** [comment]
hey had the same problem here is a temp fix:
```css
.EmeHQXR87mUskYK6xEde {
  background: none;
}
```
